server:
  port: 8080

spring:
  output.ansi.enabled: always
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql.init.mode: embedded
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug